apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes auto;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        sendfile on;
        keepalive_timeout 65;

        server {
            listen 80;
            
            location / {
                root /usr/share/nginx/html;
                index index.html;
            }

            # ✅ NUEVA CONFIGURACIÓN: Siempre devolver 200 OK en /healthz
            location /healthz {
                default_type text/plain;
                return 200 "OK";
                access_log off;
            }
        }
    }
