# 📁 PersistentVolume (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # ⬅ Agregado para compatibilidad con PVC
  volumeMode: Filesystem       # ⬅ Agregado para evitar problemas con algunos tipos de volúmenes
  hostPath:
    path: "/mnt/data"
