# 📁 PersistentVolumeClaim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard  # ⬅ Debe coincidir con el del PV
  resources:
    requests:
      storage: 500Mi  # ⬅ Puede solicitar menos que el PV, pero no más
