apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  selector:
    app: mi-app
  ports:
    - protocol: TCP
      port: 80  # Puerto dentro del cluster
      targetPort: 80
      nodePort: 30008  # Puerto que expondrá el servicio
  type: NodePort  # Exponerlo sin necesidad de Ingress
